{"error":{"message":"Could not connect to MongoDB at mongodb://0.0.0.0:27017/xerobittech","stack":"Error: Could not connect to MongoDB at mongodb://0.0.0.0:27017/xerobittech\n    at NativeConnection.SafeMongooseConnection.onError (C:\\Users\\numan\\OneDrive\\Desktop\\FYP Code\\FYP Backend\\src\\lib\\safe-mongoose-connection.ts:113:21)\n    at NativeConnection.emit (node:events:513:28)\n    at NativeConnection.emit (node:domain:489:12)\n    at C:\\Users\\numan\\OneDrive\\Desktop\\FYP Code\\FYP Backend\\node_modules\\mongoose\\lib\\connection.js:857:30\n    at processTicksAndRejections (node:internal/process/task_queues:77:11)"},"level":"error","message":"Could not connect to MongoDB at mongodb://0.0.0.0:27017/xerobittech","service":"api","timestamp":"2024-04-19T12:39:02.009Z"}
{"error":{"message":"Could not connect to MongoDB at mongodb://0.0.0.0:27017/xerobittech","stack":"Error: Could not connect to MongoDB at mongodb://0.0.0.0:27017/xerobittech\n    at NativeConnection.SafeMongooseConnection.onError (C:\\Users\\numan\\OneDrive\\Desktop\\FYP Code\\FYP Backend\\src\\lib\\safe-mongoose-connection.ts:113:21)\n    at NativeConnection.emit (node:events:513:28)\n    at NativeConnection.emit (node:domain:489:12)\n    at C:\\Users\\numan\\OneDrive\\Desktop\\FYP Code\\FYP Backend\\node_modules\\mongoose\\lib\\connection.js:857:30\n    at processTicksAndRejections (node:internal/process/task_queues:77:11)"},"level":"error","message":"Could not connect to MongoDB at mongodb://0.0.0.0:27017/xerobittech","service":"api","timestamp":"2024-04-19T12:39:34.031Z"}
{"error":{"message":"Could not connect to MongoDB at mongodb://0.0.0.0:27017/xerobittech","stack":"Error: Could not connect to MongoDB at mongodb://0.0.0.0:27017/xerobittech\n    at NativeConnection.SafeMongooseConnection.onError (C:\\Users\\numan\\OneDrive\\Desktop\\FYP Code\\FYP Backend\\src\\lib\\safe-mongoose-connection.ts:113:21)\n    at NativeConnection.emit (node:events:513:28)\n    at NativeConnection.emit (node:domain:489:12)\n    at C:\\Users\\numan\\OneDrive\\Desktop\\FYP Code\\FYP Backend\\node_modules\\mongoose\\lib\\connection.js:857:30\n    at processTicksAndRejections (node:internal/process/task_queues:77:11)"},"level":"error","message":"Could not connect to MongoDB at mongodb://0.0.0.0:27017/xerobittech","service":"api","timestamp":"2024-04-19T12:40:06.049Z"}
{"error":{"message":"Could not connect to MongoDB at mongodb://0.0.0.0:27017/xerobittech","stack":"Error: Could not connect to MongoDB at mongodb://0.0.0.0:27017/xerobittech\n    at NativeConnection.SafeMongooseConnection.onError (C:\\Users\\numan\\OneDrive\\Desktop\\FYP Code\\FYP Backend\\src\\lib\\safe-mongoose-connection.ts:113:21)\n    at NativeConnection.emit (node:events:513:28)\n    at NativeConnection.emit (node:domain:489:12)\n    at C:\\Users\\numan\\OneDrive\\Desktop\\FYP Code\\FYP Backend\\node_modules\\mongoose\\lib\\connection.js:857:30\n    at processTicksAndRejections (node:internal/process/task_queues:77:11)"},"level":"error","message":"Could not connect to MongoDB at mongodb://0.0.0.0:27017/xerobittech","service":"api","timestamp":"2024-04-19T12:40:38.065Z"}
{"error":{"message":"Could not connect to MongoDB at mongodb://0.0.0.0:27017/xerobittech","stack":"Error: Could not connect to MongoDB at mongodb://0.0.0.0:27017/xerobittech\n    at NativeConnection.SafeMongooseConnection.onError (C:\\Users\\numan\\OneDrive\\Desktop\\FYP Code\\FYP Backend\\src\\lib\\safe-mongoose-connection.ts:113:21)\n    at NativeConnection.emit (node:events:513:28)\n    at NativeConnection.emit (node:domain:489:12)\n    at C:\\Users\\numan\\OneDrive\\Desktop\\FYP Code\\FYP Backend\\node_modules\\mongoose\\lib\\connection.js:857:30\n    at processTicksAndRejections (node:internal/process/task_queues:77:11)"},"level":"error","message":"Could not connect to MongoDB at mongodb://0.0.0.0:27017/xerobittech","service":"api","timestamp":"2024-04-19T12:41:10.092Z"}
{"error":{"message":"Could not connect to MongoDB at mongodb://0.0.0.0:27017/xerobittech","stack":"Error: Could not connect to MongoDB at mongodb://0.0.0.0:27017/xerobittech\n    at NativeConnection.SafeMongooseConnection.onError (C:\\Users\\numan\\OneDrive\\Desktop\\FYP Code\\FYP Backend\\src\\lib\\safe-mongoose-connection.ts:113:21)\n    at NativeConnection.emit (node:events:513:28)\n    at NativeConnection.emit (node:domain:489:12)\n    at C:\\Users\\numan\\OneDrive\\Desktop\\FYP Code\\FYP Backend\\node_modules\\mongoose\\lib\\connection.js:857:30\n    at processTicksAndRejections (node:internal/process/task_queues:77:11)"},"level":"error","message":"Could not connect to MongoDB at mongodb://0.0.0.0:27017/xerobittech","service":"api","timestamp":"2024-04-19T12:41:42.114Z"}
{"error":{"message":"Could not connect to MongoDB at mongodb://0.0.0.0:27017/xerobittech","stack":"Error: Could not connect to MongoDB at mongodb://0.0.0.0:27017/xerobittech\n    at NativeConnection.SafeMongooseConnection.onError (C:\\Users\\numan\\OneDrive\\Desktop\\FYP Code\\FYP Backend\\src\\lib\\safe-mongoose-connection.ts:113:21)\n    at NativeConnection.emit (node:events:513:28)\n    at NativeConnection.emit (node:domain:489:12)\n    at C:\\Users\\numan\\OneDrive\\Desktop\\FYP Code\\FYP Backend\\node_modules\\mongoose\\lib\\connection.js:857:30\n    at processTicksAndRejections (node:internal/process/task_queues:77:11)"},"level":"error","message":"Could not connect to MongoDB at mongodb://0.0.0.0:27017/xerobittech","service":"api","timestamp":"2024-04-19T12:42:14.133Z"}
{"error":{"message":"Could not connect to MongoDB at mongodb://0.0.0.0:27017/xerobittech","stack":"Error: Could not connect to MongoDB at mongodb://0.0.0.0:27017/xerobittech\n    at NativeConnection.SafeMongooseConnection.onError (C:\\Users\\numan\\OneDrive\\Desktop\\FYP Code\\FYP Backend\\src\\lib\\safe-mongoose-connection.ts:113:21)\n    at NativeConnection.emit (node:events:513:28)\n    at NativeConnection.emit (node:domain:489:12)\n    at C:\\Users\\numan\\OneDrive\\Desktop\\FYP Code\\FYP Backend\\node_modules\\mongoose\\lib\\connection.js:857:30\n    at processTicksAndRejections (node:internal/process/task_queues:77:11)"},"level":"error","message":"Could not connect to MongoDB at mongodb://0.0.0.0:27017/xerobittech","service":"api","timestamp":"2024-04-19T12:42:46.155Z"}
{"error":{"message":"Could not connect to MongoDB at mongodb://0.0.0.0:27017/xerobittech","stack":"Error: Could not connect to MongoDB at mongodb://0.0.0.0:27017/xerobittech\n    at NativeConnection.SafeMongooseConnection.onError (C:\\Users\\numan\\OneDrive\\Desktop\\FYP Code\\FYP Backend\\src\\lib\\safe-mongoose-connection.ts:113:21)\n    at NativeConnection.emit (node:events:513:28)\n    at NativeConnection.emit (node:domain:489:12)\n    at C:\\Users\\numan\\OneDrive\\Desktop\\FYP Code\\FYP Backend\\node_modules\\mongoose\\lib\\connection.js:857:30\n    at processTicksAndRejections (node:internal/process/task_queues:77:11)"},"level":"error","message":"Could not connect to MongoDB at mongodb://0.0.0.0:27017/xerobittech","service":"api","timestamp":"2024-04-19T12:43:18.180Z"}
{"error":{"message":"Could not connect to MongoDB at mongodb://0.0.0.0:27017/xerobittech","stack":"Error: Could not connect to MongoDB at mongodb://0.0.0.0:27017/xerobittech\n    at NativeConnection.SafeMongooseConnection.onError (C:\\Users\\numan\\OneDrive\\Desktop\\FYP Code\\FYP Backend\\src\\lib\\safe-mongoose-connection.ts:113:21)\n    at NativeConnection.emit (node:events:513:28)\n    at NativeConnection.emit (node:domain:489:12)\n    at C:\\Users\\numan\\OneDrive\\Desktop\\FYP Code\\FYP Backend\\node_modules\\mongoose\\lib\\connection.js:857:30\n    at processTicksAndRejections (node:internal/process/task_queues:77:11)"},"level":"error","message":"Could not connect to MongoDB at mongodb://0.0.0.0:27017/xerobittech","service":"api","timestamp":"2024-04-19T12:43:50.196Z"}
{"error":{"message":"Could not connect to MongoDB at mongodb://0.0.0.0:27017/xerobittech","stack":"Error: Could not connect to MongoDB at mongodb://0.0.0.0:27017/xerobittech\n    at NativeConnection.SafeMongooseConnection.onError (C:\\Users\\numan\\OneDrive\\Desktop\\FYP Code\\FYP Backend\\src\\lib\\safe-mongoose-connection.ts:113:21)\n    at NativeConnection.emit (node:events:513:28)\n    at NativeConnection.emit (node:domain:489:12)\n    at C:\\Users\\numan\\OneDrive\\Desktop\\FYP Code\\FYP Backend\\node_modules\\mongoose\\lib\\connection.js:857:30\n    at processTicksAndRejections (node:internal/process/task_queues:77:11)"},"level":"error","message":"Could not connect to MongoDB at mongodb://0.0.0.0:27017/xerobittech","service":"api","timestamp":"2024-04-19T12:44:22.221Z"}
{"error":{"message":"Could not connect to MongoDB at mongodb://0.0.0.0:27017/xerobittech","stack":"Error: Could not connect to MongoDB at mongodb://0.0.0.0:27017/xerobittech\n    at NativeConnection.SafeMongooseConnection.onError (C:\\Users\\numan\\OneDrive\\Desktop\\FYP Code\\FYP Backend\\src\\lib\\safe-mongoose-connection.ts:113:21)\n    at NativeConnection.emit (node:events:513:28)\n    at NativeConnection.emit (node:domain:489:12)\n    at C:\\Users\\numan\\OneDrive\\Desktop\\FYP Code\\FYP Backend\\node_modules\\mongoose\\lib\\connection.js:857:30\n    at processTicksAndRejections (node:internal/process/task_queues:77:11)"},"level":"error","message":"Could not connect to MongoDB at mongodb://0.0.0.0:27017/xerobittech","service":"api","timestamp":"2024-04-19T12:44:54.236Z"}
{"error":{"message":"Could not connect to MongoDB at mongodb://0.0.0.0:27017/xerobittech","stack":"Error: Could not connect to MongoDB at mongodb://0.0.0.0:27017/xerobittech\n    at NativeConnection.SafeMongooseConnection.onError (C:\\Users\\numan\\OneDrive\\Desktop\\FYP Code\\FYP Backend\\src\\lib\\safe-mongoose-connection.ts:113:21)\n    at NativeConnection.emit (node:events:513:28)\n    at NativeConnection.emit (node:domain:489:12)\n    at C:\\Users\\numan\\OneDrive\\Desktop\\FYP Code\\FYP Backend\\node_modules\\mongoose\\lib\\connection.js:857:30\n    at processTicksAndRejections (node:internal/process/task_queues:77:11)"},"level":"error","message":"Could not connect to MongoDB at mongodb://0.0.0.0:27017/xerobittech","service":"api","timestamp":"2024-04-19T12:45:26.256Z"}
{"error":{"message":"Could not connect to MongoDB at mongodb://0.0.0.0:27017/xerobittech","stack":"Error: Could not connect to MongoDB at mongodb://0.0.0.0:27017/xerobittech\n    at NativeConnection.SafeMongooseConnection.onError (C:\\Users\\numan\\OneDrive\\Desktop\\FYP Code\\FYP Backend\\src\\lib\\safe-mongoose-connection.ts:113:21)\n    at NativeConnection.emit (node:events:513:28)\n    at NativeConnection.emit (node:domain:489:12)\n    at C:\\Users\\numan\\OneDrive\\Desktop\\FYP Code\\FYP Backend\\node_modules\\mongoose\\lib\\connection.js:857:30\n    at processTicksAndRejections (node:internal/process/task_queues:77:11)"},"level":"error","message":"Could not connect to MongoDB at mongodb://0.0.0.0:27017/xerobittech","service":"api","timestamp":"2024-04-19T12:45:58.281Z"}
{"consoleLoggerOptions":{"label":"API"},"level":"error","message":"Internal Server Error occurred while adding a new adming  , ValidationError: gender: Path `gender` is required.","service":"api","timestamp":"2024-04-27T11:48:22.114Z"}
{"consoleLoggerOptions":{"label":"API"},"level":"error","message":"Internal Server Error occurred while adding a new adming  , ValidationError: gender: Path `gender` is required.","service":"api","timestamp":"2024-04-27T11:54:39.295Z"}
{"consoleLoggerOptions":{"label":"API"},"level":"error","message":"Internal Server Error occurred while adding a new adming  , ValidationError: phoneNo: Path `phoneNo` is required.","service":"api","timestamp":"2024-04-27T12:14:45.796Z"}
